# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTIBILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.

"""
Mesh Presets System
Embedded shader → attributes mapping (generated from nani_meshes.ron)
"""

import json
from typing import Dict, List, Tuple, Optional

# Global preset manager instance
_manager: Optional['MeshPresetManager'] = None

# Embedded JSON data (generated by parse_nani_meshes.py)
NANI_MESHES_DATA = """
{
  "presets": {
    "SolidVertexColor": {
      "meshes": [
        "clutter/plant_pot_v1",
        "clutter/plant_pot_v2",
        "clutter/sunflower",
        "clutter/ladder",
        "clutter/box_w_stuff",
        "clutter/watering_can",
        "clutter/birdnest",
        "clutter/wheel",
        "clutter/pitchfork",
        "clutter/shovel",
        "clutter/firewood",
        "clutter/bucket",
        "clutter/window_flowerpot",
        "clutter/window_flower_bed_1",
        "clutter/window_flower_bed_2",
        "clutter/window_flower_bed_3",
        "clutter/window_flower_bed_4",
        "clutter/window_flower_bed_5",
        "clutter/window_flower_bed_6",
        "decorators/chimney_roof",
        "decorators/chimney_side",
        "decorators/vent_pipe",
        "decorators/door",
        "decorators/flag_roof_beam",
        "decorators/flag_wall_beam",
        "decorators/flag_corner_beam",
        "decorators/flag_wall_beam_no_connection",
        "decorators/flag_corner_beam_no_connection",
        "decorators/lantern_terrain",
        "decorators/lantern_terrain_inside",
        "decorators/lantern_wall",
        "decorators/lantern_wall_inside",
        "decorators/lantern_flat_roof",
        "decorators/lantern_flat_roof_inside",
        "decorators/setdressing_clothline_thread",
        "decorators/setdressing_clothline_beam",
        "decorators/setdressing_flower_bed",
        "decorators/setdressing_flower_pot",
        "decorators/setdressing_flower_pot_2",
        "decorators/setdressing_flower_pot_hanging_1",
        "decorators/setdressing_flower_pot_hanging_2",
        "decorators/setdressing_flower_pot_purple",
        "decorators/setdressing_flower_pot_red",
        "decorators/window_cottage_1x1_glass_broken_0",
        "decorators/window_cottage_1x1_glass_broken_1",
        "decorators/window_cottage_1x1_glass_broken_2",
        "sewage_gate_bar",
        "wooden_gate/door_handle_circle",
        "fish",
        "clutter/fabric_rolls",
        "clutter/door_bell",
        "clutter/door_krans",
        "clutter/door_krans_autumn"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position"
      ],
      "optional_attributes": [
        "flags"
      ]
    },
    "SolidVertexColorWindow": {
      "meshes": [
        "clutter/window_shutter",
        "decorators/setdressing_window_lintel",
        "decorators/setdressing_window_sill",
        "decorators/window_cottage_1x1",
        "decorators/window_cottage_1x1_corner",
        "decorators/window_cottage_1x1_dormer",
        "decorators/window_cottage_1x1_dormer_frame",
        "decorators/window_cottage_1x1_full_dormer",
        "decorators/window_cottage_1x1_full_dormer_corner",
        "decorators/window_cottage_1x1_halfdormer_frame",
        "decorators/window_cottage_2x1",
        "decorators/window_cottage_2x1_full_dormer",
        "decorators/window_cottage_2x1_halfdormer_frame",
        "decorators/window_cottage_3x1",
        "decorators/window_cottage_3x1_full_dormer",
        "decorators/window_cottage_3x1_halfdormer_frame",
        "decorators/window_cottage_corner_1x1",
        "decorators/window_cottage_corner_1x1_sill",
        "decorators/window_cottage_corner_2x1",
        "decorators/window_cottage_corner_3x1",
        "decorators/window_gothic_1x1",
        "decorators/window_gothic_2x1",
        "decorators/window_gothic_3x1",
        "decorators/window_gothic_1x1_dormer",
        "decorators/window_gothic_2x1_dormer",
        "decorators/window_gothic_3x1_dormer",
        "decorators/balcony_door_rank1_rails",
        "decorators/balcony_door_rank2_rails",
        "decorators/balcony_door_rank3_rails",
        "decorators/gothic_balcony_door_rank1_rails",
        "decorators/gothic_balcony_door_rank2_rails",
        "decorators/gothic_balcony_door_rank3_rails",
        "decorators/arrow_slit_1x1",
        "decorators/arrow_slit_1x2",
        "decorators/arrow_slit_1x3",
        "decorators/arrow_slit_1x3_halfdormer"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV"
      ],
      "optional_attributes": []
    },
    "SolidVertexColorWindowGlass": {
      "meshes": [
        "decorators/window_cottage_1x1_dormer_glass",
        "decorators/window_cottage_1x1_glass",
        "decorators/window_cottage_2x1_glass",
        "decorators/window_cottage_3x1_glass",
        "decorators/window_cottage_corner_1x1_glass",
        "decorators/window_cottage_corner_2x1_glass",
        "decorators/window_cottage_corner_3x1_glass",
        "decorators/window_gothic_1x1_glass",
        "decorators/window_gothic_2x1_glass",
        "decorators/window_gothic_3x1_glass",
        "decorators/window_gothic_1x1_dormer_glass",
        "decorators/window_gothic_2x1_dormer_glass",
        "decorators/window_gothic_3x1_dormer_glass",
        "decorators/arrow_slit_1x1_glass",
        "decorators/arrow_slit_1x2_glass",
        "decorators/arrow_slit_1x3_glass"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV"
      ],
      "optional_attributes": [
        "is_glass"
      ]
    },
    "SolidVertexColorBricks": {
      "meshes": [
        "decorators/arrow_slit_1x1",
        "decorators/arrow_slit_1x2",
        "decorators/arrow_slit_1x3",
        "decorators/arrow_slit_1x3_halfdormer",
        "decorators/window_gothic_1x1_dormer",
        "decorators/window_gothic_2x1_dormer",
        "decorators/window_gothic_3x1_dormer",
        "decorators/window_gothic_1x1",
        "decorators/window_gothic_2x1",
        "decorators/window_gothic_3x1",
        "decorators/window_gothic_1x1_hat_full",
        "decorators/window_gothic_1x1_hat"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "bitangent",
        "tangent"
      ],
      "optional_attributes": []
    },
    "GothicWindowBricks": {
      "meshes": [
        "decorators/arrow_slit_1x2_hat",
        "decorators/arrow_slit_1x3_hat",
        "decorators/balcony_door_gothic_rank1_hat",
        "decorators/balcony_door_gothic_rank2_hat",
        "decorators/balcony_door_gothic_rank3_hat",
        "decorators/window_gothic_2x1_hat_full",
        "decorators/window_gothic_3x1_hat_full",
        "decorators/window_gothic_2x1_hat",
        "decorators/window_gothic_3x1_hat"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "bbx_x",
        "bitangent",
        "brick_id",
        "is_bevel",
        "tangent"
      ],
      "optional_attributes": []
    },
    "RoofTile": {
      "meshes": [
        "roof_tile",
        "roof_tile_lod1",
        "roof_tile_backface"
      ],
      "common_attributes": [
        "Vertex_Position"
      ],
      "optional_attributes": []
    },
    "Plant": {
      "meshes": [
        "clutter/reed",
        "clutter/lilypad",
        "fallen_leaves",
        "fallen_petals"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "stem",
        "wind_bend"
      ],
      "optional_attributes": []
    },
    "Flower": {
      "meshes": [
        "garden_flower_01_lavender",
        "garden_flower_02",
        "bush_flowers"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "autumn_color",
        "flowery_color",
        "wind_bend"
      ],
      "optional_attributes": []
    },
    "Bush": {
      "meshes": [
        "bush_body"
      ],
      "common_attributes": [
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "bush_part_id"
      ],
      "optional_attributes": []
    },
    "WoodenPlank": {
      "meshes": [
        "wooden_plank",
        "wooden_plank_lod1",
        "wooden_plank_straight"
      ],
      "common_attributes": [
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "is_bevel"
      ],
      "optional_attributes": []
    },
    "PreplacedFlower": {
      "meshes": [
        "flowery_lavender"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "wind_bend"
      ],
      "optional_attributes": []
    },
    "SolidAlbedoMap": {
      "meshes": [
        "tree_log",
        "tree_stump",
        "olden_glade_rock",
        "clutter/bench",
        "clutter/bench_short",
        "clutter/bench_w_basket",
        "clutter/barrel",
        "clutter/haystack",
        "clutter/birdhouse",
        "clutter/basket",
        "clutter/basket_w_food",
        "clutter/barrel_w_food_basket",
        "clutter/potato_sack",
        "clutter/road_sign",
        "clutter/cart",
        "clutter/cart2",
        "clutter/crates_w_tools",
        "clutter/crates_w_flowers",
        "clutter/pumpkin",
        "clutter/pumpkin2",
        "clutter/anvil",
        "clutter/stall_bread",
        "clutter/stall_veggies",
        "clutter/crate_fish",
        "clutter/rack_brooms",
        "clutter/flowerbox",
        "clutter/crates_w_pumpkins_regular",
        "clutter/cart_w_pumpkins_regular"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV"
      ],
      "optional_attributes": [
        "flags"
      ]
    },
    "SolidAlbedoMapEmissive": {
      "meshes": [
        "clutter/pumpkin_w_face",
        "clutter/cart_w_pumpkins",
        "clutter/crates_w_pumpkins",
        "clutter/barrel_w_candles"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV"
      ],
      "optional_attributes": []
    },
    "Wren": {
      "meshes": [
        "small_bird"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "is_wing",
        "rest_n",
        "rest_pos",
        "wing_t"
      ],
      "optional_attributes": []
    },
    "LanternEmissive": {
      "meshes": [
        "decorators/lantern_wall_inside",
        "decorators/lantern_terrain_inside",
        "decorators/lantern_flat_roof_inside"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position"
      ],
      "optional_attributes": []
    },
    "Cloth": {
      "meshes": [
        "decorators/setdressing_clothline_cloth",
        "decorators/setdressing_clothline_cloth_2"
      ],
      "common_attributes": [
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "bitangent",
        "tangent"
      ],
      "optional_attributes": []
    },
    "BalconyDoor": {
      "meshes": [
        "decorators/balcony_door_rank1",
        "decorators/balcony_door_rank2",
        "decorators/balcony_door_rank3",
        "decorators/balcony_door_gothic_rank1",
        "decorators/balcony_door_gothic_rank2",
        "decorators/balcony_door_gothic_rank3",
        "decorators/trap_door_cottage",
        "decorators/trap_door_gothic"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV",
        "is_metal_part"
      ],
      "optional_attributes": []
    },
    "Uber": {
      "meshes": [
        "decorators/flag_terrain_support",
        "decorators/lantern_terrain_support"
      ],
      "common_attributes": [
        "Vertex_Color",
        "Vertex_Normal",
        "Vertex_Position",
        "Vertex_UV"
      ],
      "optional_attributes": []
    },
    "VelocityOnly": {
      "meshes": [
        "clutter/cart",
        "clutter/cart2",
        "clutter/cart_w_pumpkins_regular",
        "clutter/cart_w_pumpkins"
      ],
      "common_attributes": [
        "Vertex_Position"
      ],
      "optional_attributes": []
    }
  },
   "mesh_to_preset": {
    "background_tree": "None",
    "billboard_plants": "None",
    "billboard_plants_2": "None",
    "branch_billboard": "None",
    "branches": "None",
    "branchy_tree_v1": "None",
    "branchy_tree_v1_particle_spawner": "None",
    "branchy_tree_v1_particles": "None",
    "branchy_tree_v2 original": "None",
    "branchy_tree_v2": "None",
    "branchy_tree_v2_particle_spawner": "None",
    "branchy_tree_v2_particles": "None",
    "branchy_tree_v3": "None",
    "branchy_tree_v3_particle_spawner": "None",
    "branchy_tree_v3_particles": "None",
    "brick": "None",
    "brush_2_arrows": "None",
    "brush_4_arrows": "None",
    "brush_5_replay": "None",
    "brush_arrow": "None",
    "brush_arrow_flat": "None",
    "brush_arrow_flat_outline": "None",
    "brush_arrow_flat_single_foward": "None",
    "brush_arrow_flat_single_up": "None",
    "brush_circle": "None",
    "brush_circle_cross": "None",
    "brush_circle_scribble": "None",
    "bush": "None",
    "bush_body": "Bush",
    "bush_flowers": "Flower",
    "butterfly": "None",
    "central_tree": "None",
    "clover": "None",
    "clover_flowers": "None",
    "corner_arrow": "None",
    "corner_arrow_outline": "None",
    "corner_arrow_switch_ridge_dir": "None",
    "dashed_circle": "None",
    "dashed_lines": "None",
    "decorator_delete_scribble": "None",
    "decorator_outline": "None",
    "decorator_test": "None",
    "decorator_test_cupola": "None",
    "decorator_test_door": "None",
    "decorator_test_dormer": "None",
    "decorator_test_turret": "None",
    "decorator_trigger_volume": "None",
    "distant_billboard": "None",
    "duck_flying": "None",
    "duck_heart": "None",
    "fallen_leaves": "Plant",
    "fallen_petals": "Plant",
    "fallen_tree": "None",
    "far_distance_tree": "None",
    "fish": "SolidVertexColor",
    "flat_arrow": "None",
    "flat_arrow_outline": "None",
    "floatie": "None",
    "flowery_lavender": "PreplacedFlower",
    "forest_terrain": "None",
    "garden_flower_01_lavender": "Flower",
    "garden_flower_02": "Flower",
    "garden_stone": "None",
    "hand": "None",
    "ice_cracks": "None",
    "ivy_branch": "None",
    "ivy_flower": "None",
    "ivy_leaf": "None",
    "japanese_pine_tree": "None",
    "japanese_pine_tree2": "None",
    "lantern_flat_roof": "None",
    "lavender": "None",
    "lilypad": "None",
    "lilypad_flower": "None",
    "logo_branches": "None",
    "lowpoly_flower": "None",
    "meadow_lowpoly_flowers": "None",
    "mid_distance_tree_v1": "None",
    "mid_distance_tree_v1_particle_spawner": "None",
    "mid_distance_tree_v1_particles": "None",
    "mid_distance_tree_v1_trunk": "None",
    "mid_distance_tree_v2": "None",
    "mid_distance_tree_v2_particle_spawner": "None",
    "mid_distance_tree_v2_particles": "None",
    "mid_distance_tree_v2_trunk": "None",
    "mid_tree_v3": "None",
    "mid_tree_v3_trunk": "None",
    "mid_tree_v4": "None",
    "mid_tree_v4_trunk": "None",
    "mid_tree_v5": "None",
    "mid_tree_v5_trunk": "None",
    "move_shape": "None",
    "move_shape_outline": "None",
    "naked_tree_1": "None",
    "naked_tree_1_no_mushrooms": "None",
    "naked_tree_2": "None",
    "naked_tree_2_lowpoly": "None",
    "naked_tree_2_no_mushrooms": "None",
    "olden_glade_rock": "SolidAlbedoMap",
    "olden_tree": "None",
    "olden_tree_large": "None",
    "particle_plane": "None",
    "path_pebble": "None",
    "pine_tree_v1_particle_spawner ": "None",
    "pine_tree_v1_particles": "None",
    "plant_leafy": "None",
    "plant_thistle": "None",
    "rain_particles": "None",
    "reed": "None",
    "reed_autumn": "None",
    "roof_button": "None",
    "roof_delete_scribble": "None",
    "roof_spire": "None",
    "roof_support_beam": "None",
    "roof_tile": "RoofTile",
    "roof_tile_backface": "RoofTile",
    "roof_tile_lod1": "RoofTile",
    "scissors": "None",
    "sewage_gate_bar": "SolidVertexColor",
    "sheep_heart": "None",
    "skydome": "None",
    "small_bird": "Wren",
    "sparkle": "None",
    "splash": "None",
    "stair_step": "None",
    "stairs_pebble": "None",
    "stairs_step": "None",
    "table_short": "None",
    "terrain": "None",
    "terrain_rocks": "None",
    "tiny_glade_logo": "None",
    "tree_billboard": "None",
    "tree_log": "SolidAlbedoMap",
    "tree_stump": "SolidAlbedoMap",
    "umbrella": "None",
    "water_grass_winter": "None",
    "water_plane": "None",
    "water_stones": "None",
    "window_cottage_1x1": "None",
    "wooden_plank": "WoodenPlank",
    "wooden_plank_lod1": "WoodenPlank",
    "wooden_plank_straight": "WoodenPlank",
    "clutter/anvil": "SolidAlbedoMap",
    "clutter/barrel": "SolidAlbedoMap",
    "clutter/barrel_w_candles": "SolidAlbedoMapEmissive",
    "clutter/barrel_w_food_basket": "SolidAlbedoMap",
    "clutter/basket": "SolidAlbedoMap",
    "clutter/basket_w_food": "SolidAlbedoMap",
    "clutter/bench": "SolidAlbedoMap",
    "clutter/bench_short": "SolidAlbedoMap",
    "clutter/bench_w_basket": "SolidAlbedoMap",
    "clutter/birdhouse": "SolidAlbedoMap",
    "clutter/birdnest": "SolidVertexColor",
    "clutter/box_w_stuff": "SolidVertexColor",
    "clutter/bucket": "SolidVertexColor",
    "clutter/cart": "SolidAlbedoMap",
    "clutter/cart2": "SolidAlbedoMap",
    "clutter/cart_w_pumpkins": "SolidAlbedoMapEmissive",
    "clutter/cart_w_pumpkins_regular": "SolidAlbedoMap",
    "clutter/chimney_side": "None",
    "clutter/crate_fish": "SolidAlbedoMap",
    "clutter/crates_w_flowers": "SolidAlbedoMap",
    "clutter/crates_w_pumpkins": "SolidAlbedoMapEmissive",
    "clutter/crates_w_pumpkins_regular": "SolidAlbedoMap",
    "clutter/crates_w_tools": "SolidAlbedoMap",
    "clutter/door_bell": "SolidVertexColor",
    "clutter/door_krans": "SolidVertexColor",
    "clutter/door_krans_autumn": "SolidVertexColor",
    "clutter/fabric_rolls": "SolidVertexColor",
    "clutter/firewood": "SolidVertexColor",
    "clutter/flowerbox": "SolidAlbedoMap",
    "clutter/haystack": "SolidAlbedoMap",
    "clutter/ladder": "SolidVertexColor",
    "clutter/lilypad": "Plant",
    "clutter/market_stall_bread": "None",
    "clutter/pitchfork": "SolidVertexColor",
    "clutter/plant_pot_v1": "SolidVertexColor",
    "clutter/plant_pot_v2": "SolidVertexColor",
    "clutter/potato_sack": "SolidAlbedoMap",
    "clutter/pumpkin": "SolidAlbedoMap",
    "clutter/pumpkin2": "SolidAlbedoMap",
    "clutter/pumpkin_w_face": "SolidAlbedoMapEmissive",
    "clutter/rack_brooms": "SolidAlbedoMap",
    "clutter/rake_01": "None",
    "clutter/reed": "Plant",
    "clutter/road_sign": "SolidAlbedoMap",
    "clutter/short_bench": "None",
    "clutter/shovel": "SolidVertexColor",
    "clutter/stall_bread": "SolidAlbedoMap",
    "clutter/stall_veggies": "SolidAlbedoMap",
    "clutter/sunflower": "SolidVertexColor",
    "clutter/watering_can": "SolidVertexColor",
    "clutter/wheel": "SolidVertexColor",
    "clutter/window_flower_bed_1": "SolidVertexColor",
    "clutter/window_flower_bed_2": "SolidVertexColor",
    "clutter/window_flower_bed_3": "SolidVertexColor",
    "clutter/window_flower_bed_4": "SolidVertexColor",
    "clutter/window_flower_bed_5": "SolidVertexColor",
    "clutter/window_flower_bed_6": "SolidVertexColor",
    "clutter/window_flowerpot": "SolidVertexColor",
    "clutter/window_shutter": "SolidVertexColorWindow",
    "decorators/arrow_slit_1x1": "SolidVertexColorWindow",
    "decorators/arrow_slit_1x1_collision": "None",
    "decorators/arrow_slit_1x1_glass": "SolidVertexColorWindowGlass",
    "decorators/arrow_slit_1x1_interaction": "None",
    "decorators/arrow_slit_1x1_outline": "None",
    "decorators/arrow_slit_1x2": "SolidVertexColorWindow",
    "decorators/arrow_slit_1x2_collision": "None",
    "decorators/arrow_slit_1x2_glass": "SolidVertexColorWindowGlass",
    "decorators/arrow_slit_1x2_hat": "GothicWindowBricks",
    "decorators/arrow_slit_1x2_interaction": "None",
    "decorators/arrow_slit_1x2_outline": "None",
    "decorators/arrow_slit_1x3": "SolidVertexColorWindow",
    "decorators/arrow_slit_1x3_collision": "None",
    "decorators/arrow_slit_1x3_glass": "SolidVertexColorWindowGlass",
    "decorators/arrow_slit_1x3_halfdormer": "SolidVertexColorWindow",
    "decorators/arrow_slit_1x3_hat": "GothicWindowBricks",
    "decorators/arrow_slit_1x3_interaction": "None",
    "decorators/arrow_slit_1x3_outline": "None",
    "decorators/balcony_door_gothic_rank1": "BalconyDoor",
    "decorators/balcony_door_gothic_rank1_collision": "None",
    "decorators/balcony_door_gothic_rank1_collision_outline": "None",
    "decorators/balcony_door_gothic_rank1_hat": "GothicWindowBricks",
    "decorators/balcony_door_gothic_rank1_interaction": "None",
    "decorators/balcony_door_gothic_rank1_outline": "None",
    "decorators/balcony_door_gothic_rank2": "BalconyDoor",
    "decorators/balcony_door_gothic_rank2_collision": "None",
    "decorators/balcony_door_gothic_rank2_collision_outline": "None",
    "decorators/balcony_door_gothic_rank2_hat": "GothicWindowBricks",
    "decorators/balcony_door_gothic_rank2_interaction": "None",
    "decorators/balcony_door_gothic_rank2_outline": "None",
    "decorators/balcony_door_gothic_rank3": "BalconyDoor",
    "decorators/balcony_door_gothic_rank3_collision": "None",
    "decorators/balcony_door_gothic_rank3_collision_outline": "None",
    "decorators/balcony_door_gothic_rank3_hat": "GothicWindowBricks",
    "decorators/balcony_door_gothic_rank3_interaction": "None",
    "decorators/balcony_door_gothic_rank3_outline": "None",
    "decorators/balcony_door_rank1": "BalconyDoor",
    "decorators/balcony_door_rank1_collision": "None",
    "decorators/balcony_door_rank1_interaction": "None",
    "decorators/balcony_door_rank1_rails": "SolidVertexColorWindow",
    "decorators/balcony_door_rank2": "BalconyDoor",
    "decorators/balcony_door_rank2_collision": "None",
    "decorators/balcony_door_rank2_interaction": "None",
    "decorators/balcony_door_rank2_rails": "SolidVertexColorWindow",
    "decorators/balcony_door_rank3": "BalconyDoor",
    "decorators/balcony_door_rank3_collision": "None",
    "decorators/balcony_door_rank3_interaction": "None",
    "decorators/balcony_door_rank3_rails": "SolidVertexColorWindow",
    "decorators/balcony_door_single": "None",
    "decorators/birdnest": "None",
    "decorators/chimney_collision": "None",
    "decorators/chimney_collision_outline": "None",
    "decorators/chimney_collision_outline_roof": "None",
    "decorators/chimney_collision_outline_vent_pipe": "None",
    "decorators/chimney_roof": "SolidVertexColor",
    "decorators/chimney_side": "SolidVertexColor",
    "decorators/door": "SolidVertexColor",
    "decorators/flag_corner_beam": "SolidVertexColor",
    "decorators/flag_corner_beam_no_connection": "SolidVertexColor",
    "decorators/flag_corner_collision": "None",
    "decorators/flag_corner_collision_outline": "None",
    "decorators/flag_line": "None",
    "decorators/flag_roof_beam": "SolidVertexColor",
    "decorators/flag_roof_cloth": "None",
    "decorators/flag_roof_collision": "None",
    "decorators/flag_roof_collision_outline": "None",
    "decorators/flag_roof_interaction": "None",
    "decorators/flag_terrain_collision": "None",
    "decorators/flag_terrain_interaction": "None",
    "decorators/flag_terrain_support": "Uber",
    "decorators/flag_wall": "None",
    "decorators/flag_wall_beam": "SolidVertexColor",
    "decorators/flag_wall_beam_no_connection": "SolidVertexColor",
    "decorators/flag_wall_collision": "None",
    "decorators/flag_wall_collision_outline": "None",
    "decorators/flag_wall_interaction": "None",
    "decorators/gothic_balcony_door_rank1_rails": "SolidVertexColorWindow",
    "decorators/gothic_balcony_door_rank2_rails": "SolidVertexColorWindow",
    "decorators/gothic_balcony_door_rank3_rails": "SolidVertexColorWindow",
    "decorators/lantern_collision": "None",
    "decorators/lantern_flat": "None",
    "decorators/lantern_flat_roof": "SolidVertexColor",
    "decorators/lantern_flat_roof2": "None",
    "decorators/lantern_flat_roof_collision": "None",
    "decorators/lantern_flat_roof_collision_outline": "None",
    "decorators/lantern_flat_roof_inside": "SolidVertexColor",
    "decorators/lantern_flat_roof_inside2": "None",
    "decorators/lantern_terrain": "SolidVertexColor",
    "decorators/lantern_terrain_collision": "None",
    "decorators/lantern_terrain_inside": "SolidVertexColor",
    "decorators/lantern_terrain_interaction": "None",
    "decorators/lantern_terrain_old": "None",
    "decorators/lantern_terrain_outline": "None",
    "decorators/lantern_terrain_rotate_collision": "None",
    "decorators/lantern_terrain_support": "Uber",
    "decorators/lantern_wall": "SolidVertexColor",
    "decorators/lantern_wall_collision": "None",
    "decorators/lantern_wall_collision_outline": "None",
    "decorators/lantern_wall_inside": "SolidVertexColor",
    "decorators/lantern_wall_interaction": "None",
    "decorators/outline_balcony_door_rank1": "None",
    "decorators/outline_balcony_door_rank2": "None",
    "decorators/outline_balcony_door_rank3": "None",
    "decorators/outline_cottage_window_1": "None",
    "decorators/outline_cottage_window_2": "None",
    "decorators/outline_cottage_window_3": "None",
    "decorators/outline_gothic_window_1": "None",
    "decorators/outline_gothic_window_2": "None",
    "decorators/outline_gothic_window_3": "None",
    "decorators/outline_window_cottage_1x1_full_dormer": "None",
    "decorators/outline_window_cottage_2x1_full_dormer": "None",
    "decorators/outline_window_cottage_3x1_full_dormer": "None",
    "decorators/outline_window_cottage_corner_1x1": "None",
    "decorators/outline_window_cottage_corner_2x1": "None",
    "decorators/outline_window_cottage_corner_3x1": "None",
    "decorators/setdressing_cloth": "None",
    "decorators/setdressing_clothline_beam": "SolidVertexColor",
    "decorators/setdressing_clothline_cloth": "Cloth",
    "decorators/setdressing_clothline_cloth_2": "Cloth",
    "decorators/setdressing_clothline_thread": "SolidVertexColor",
    "decorators/setdressing_flower_bed": "SolidVertexColor",
    "decorators/setdressing_flower_pot": "SolidVertexColor",
    "decorators/setdressing_flower_pot_2": "SolidVertexColor",
    "decorators/setdressing_flower_pot_hanging_1": "SolidVertexColor",
    "decorators/setdressing_flower_pot_hanging_2": "SolidVertexColor",
    "decorators/setdressing_flower_pot_purple": "SolidVertexColor",
    "decorators/setdressing_flower_pot_red": "SolidVertexColor",
    "decorators/setdressing_window_lintel": "SolidVertexColorWindow",
    "decorators/setdressing_window_sill": "SolidVertexColorWindow",
    "decorators/trap_door_cottage": "BalconyDoor",
    "decorators/trap_door_cottage_collision": "None",
    "decorators/trap_door_cottage_collision_outline": "None",
    "decorators/trap_door_cottage_outline": "None",
    "decorators/trap_door_gothic": "BalconyDoor",
    "decorators/vent_pipe": "SolidVertexColor",
    "decorators/vent_pipe_collision": "None",
    "decorators/window_cottage_1x1": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_collision": "None",
    "decorators/window_cottage_1x1_collision_outline": "None",
    "decorators/window_cottage_1x1_corner": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_dormer": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_dormer_frame": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_dormer_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_1x1_flowerbed_locations": "None",
    "decorators/window_cottage_1x1_full_dormer": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_full_dormer_collision_outline": "None",
    "decorators/window_cottage_1x1_full_dormer_corner": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_1x1_glass_broken_0": "SolidVertexColor",
    "decorators/window_cottage_1x1_glass_broken_1": "SolidVertexColor",
    "decorators/window_cottage_1x1_glass_broken_2": "SolidVertexColor",
    "decorators/window_cottage_1x1_halfdormer_collision": "None",
    "decorators/window_cottage_1x1_halfdormer_frame": "SolidVertexColorWindow",
    "decorators/window_cottage_1x1_interaction": "None",
    "decorators/window_cottage_2x1": "SolidVertexColorWindow",
    "decorators/window_cottage_2x1_collision": "None",
    "decorators/window_cottage_2x1_collision_outline": "None",
    "decorators/window_cottage_2x1_flowerbed_locations": "None",
    "decorators/window_cottage_2x1_full_dormer": "SolidVertexColorWindow",
    "decorators/window_cottage_2x1_full_dormer_collision_outline": "None",
    "decorators/window_cottage_2x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_2x1_halfdormer_collision": "None",
    "decorators/window_cottage_2x1_halfdormer_frame": "SolidVertexColorWindow",
    "decorators/window_cottage_2x1_interaction": "None",
    "decorators/window_cottage_3x1": "SolidVertexColorWindow",
    "decorators/window_cottage_3x1_collision": "None",
    "decorators/window_cottage_3x1_collision_outline": "None",
    "decorators/window_cottage_3x1_flowerbed_locations": "None",
    "decorators/window_cottage_3x1_full_dormer": "SolidVertexColorWindow",
    "decorators/window_cottage_3x1_full_dormer_collision_outline": "None",
    "decorators/window_cottage_3x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_3x1_halfdormer_collision": "None",
    "decorators/window_cottage_3x1_halfdormer_frame": "SolidVertexColorWindow",
    "decorators/window_cottage_3x1_interaction": "None",
    "decorators/window_cottage_4x1_halfdormer_collision": "None",
    "decorators/window_cottage_corner_1x1": "SolidVertexColorWindow",
    "decorators/window_cottage_corner_1x1_collision": "None",
    "decorators/window_cottage_corner_1x1_flowerbed_locations": "None",
    "decorators/window_cottage_corner_1x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_corner_1x1_interaction": "None",
    "decorators/window_cottage_corner_1x1_sill": "SolidVertexColorWindow",
    "decorators/window_cottage_corner_2x1": "SolidVertexColorWindow",
    "decorators/window_cottage_corner_2x1_collision": "None",
    "decorators/window_cottage_corner_2x1_flowerbed_locations": "None",
    "decorators/window_cottage_corner_2x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_corner_2x1_interaction": "None",
    "decorators/window_cottage_corner_3x1": "SolidVertexColorWindow",
    "decorators/window_cottage_corner_3x1_collision": "None",
    "decorators/window_cottage_corner_3x1_flowerbed_locations": "None",
    "decorators/window_cottage_corner_3x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_cottage_corner_3x1_interaction": "None",
    "decorators/window_gothic_1x1": "SolidVertexColorWindow",
    "decorators/window_gothic_1x1_collision": "None",
    "decorators/window_gothic_1x1_collision_outline": "None",
    "decorators/window_gothic_1x1_dormer": "SolidVertexColorWindow",
    "decorators/window_gothic_1x1_dormer_collision": "None",
    "decorators/window_gothic_1x1_dormer_collision_outline": "None",
    "decorators/window_gothic_1x1_dormer_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_1x1_dormer_interaction": "None",
    "decorators/window_gothic_1x1_dormer_outline": "None",
    "decorators/window_gothic_1x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_1x1_hat": "SolidVertexColorBricks",
    "decorators/window_gothic_1x1_hat_full": "SolidVertexColorBricks",
    "decorators/window_gothic_1x1_interaction": "None",
    "decorators/window_gothic_1x1_outline": "None",
    "decorators/window_gothic_2x1": "SolidVertexColorWindow",
    "decorators/window_gothic_2x1_collision": "None",
    "decorators/window_gothic_2x1_collision_outline": "None",
    "decorators/window_gothic_2x1_dormer": "SolidVertexColorWindow",
    "decorators/window_gothic_2x1_dormer_collision": "None",
    "decorators/window_gothic_2x1_dormer_collision_outline": "None",
    "decorators/window_gothic_2x1_dormer_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_2x1_dormer_interaction": "None",
    "decorators/window_gothic_2x1_dormer_outline": "None",
    "decorators/window_gothic_2x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_2x1_hat": "GothicWindowBricks",
    "decorators/window_gothic_2x1_hat_full": "GothicWindowBricks",
    "decorators/window_gothic_2x1_interaction": "None",
    "decorators/window_gothic_2x1_outline": "None",
    "decorators/window_gothic_3x1": "SolidVertexColorWindow",
    "decorators/window_gothic_3x1_collision": "None",
    "decorators/window_gothic_3x1_collision_outline": "None",
    "decorators/window_gothic_3x1_dormer": "SolidVertexColorWindow",
    "decorators/window_gothic_3x1_dormer_collision": "None",
    "decorators/window_gothic_3x1_dormer_collision_outline": "None",
    "decorators/window_gothic_3x1_dormer_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_3x1_dormer_interaction": "None",
    "decorators/window_gothic_3x1_dormer_outline": "None",
    "decorators/window_gothic_3x1_glass": "SolidVertexColorWindowGlass",
    "decorators/window_gothic_3x1_hat": "GothicWindowBricks",
    "decorators/window_gothic_3x1_hat_full": "GothicWindowBricks",
    "decorators/window_gothic_3x1_interaction": "None",
    "decorators/window_gothic_3x1_outline": "None",
    "sheep_animation/1": "None",
    "sheep_animation/10": "None",
    "sheep_animation/11": "None",
    "sheep_animation/12": "None",
    "sheep_animation/13": "None",
    "sheep_animation/14": "None",
    "sheep_animation/15": "None",
    "sheep_animation/16": "None",
    "sheep_animation/17": "None",
    "sheep_animation/18": "None",
    "sheep_animation/19": "None",
    "sheep_animation/2": "None",
    "sheep_animation/20": "None",
    "sheep_animation/21": "None",
    "sheep_animation/22": "None",
    "sheep_animation/23": "None",
    "sheep_animation/24": "None",
    "sheep_animation/25": "None",
    "sheep_animation/26": "None",
    "sheep_animation/27": "None",
    "sheep_animation/28": "None",
    "sheep_animation/29": "None",
    "sheep_animation/3": "None",
    "sheep_animation/30": "None",
    "sheep_animation/4": "None",
    "sheep_animation/5": "None",
    "sheep_animation/6": "None",
    "sheep_animation/7": "None",
    "sheep_animation/8": "None",
    "sheep_animation/9": "None",
    "sheep_animation/delighted": "None",
    "sheep_animation/sheep_bee1": "None",
    "sheep_animation/sheep_bee2": "None",
    "sheep_animation/sheep_rainbow_1": "None",
    "terrain_rt/chunk_0": "None",
    "terrain_rt/chunk_1": "None",
    "terrain_rt/chunk_10": "None",
    "terrain_rt/chunk_11": "None",
    "terrain_rt/chunk_12": "None",
    "terrain_rt/chunk_13": "None",
    "terrain_rt/chunk_14": "None",
    "terrain_rt/chunk_15": "None",
    "terrain_rt/chunk_16": "None",
    "terrain_rt/chunk_17": "None",
    "terrain_rt/chunk_18": "None",
    "terrain_rt/chunk_19": "None",
    "terrain_rt/chunk_2": "None",
    "terrain_rt/chunk_20": "None",
    "terrain_rt/chunk_21": "None",
    "terrain_rt/chunk_22": "None",
    "terrain_rt/chunk_23": "None",
    "terrain_rt/chunk_24": "None",
    "terrain_rt/chunk_25": "None",
    "terrain_rt/chunk_26": "None",
    "terrain_rt/chunk_27": "None",
    "terrain_rt/chunk_28": "None",
    "terrain_rt/chunk_29": "None",
    "terrain_rt/chunk_3": "None",
    "terrain_rt/chunk_30": "None",
    "terrain_rt/chunk_31": "None",
    "terrain_rt/chunk_4": "None",
    "terrain_rt/chunk_5": "None",
    "terrain_rt/chunk_6": "None",
    "terrain_rt/chunk_7": "None",
    "terrain_rt/chunk_8": "None",
    "terrain_rt/chunk_9": "None",
    "wooden_gate/door_handle_circle": "SolidVertexColor",
    "wooden_gate/ladder": "None"
  }
}
"""


class MeshPresetManager:
    """Manages shader presets and mesh attribute mappings"""
    
    def __init__(self):
        self.loaded = False
        
        # Data structures
        self.mesh_to_preset: Dict[str, Tuple[str, List[str], List[str]]] = {}
        # mesh_name → (subset_name, common_attributes, optional_attributes)
        
        self.presets: Dict[str, Dict] = {}
        # subset_name → {
        #     'meshes': [list of mesh names],
        #     'common_attributes': [...],
        #     'optional_attributes': [...],
        #     'remove': [...]
        # }
    
    def load(self) -> bool:
        """Load presets from embedded JSON data. Returns True if successful."""
        if self.loaded:
            return True
        
        try:
            # Parse embedded JSON data
            data = json.loads(NANI_MESHES_DATA)
            
            # Load presets
            self.presets = data.get('presets', {})
            
            # Build mesh_to_preset mapping
            mesh_to_preset_raw = data.get('mesh_to_preset', {})
            for mesh_name, preset_name in mesh_to_preset_raw.items():
                if preset_name in self.presets:
                    preset = self.presets[preset_name]
                    required = preset.get('common_attributes', [])
                    optional = preset.get('optional_attributes', [])
                    self.mesh_to_preset[mesh_name] = (preset_name, required, optional)
            
            self.loaded = True
            return True
            
        except (json.JSONDecodeError, KeyError) as e:
            print(f"Failed to load embedded presets: {e}")
            self.loaded = False
            return False
    
    def get_preset_list(self) -> List[str]:
        """Get list of all preset names"""
        if not self.loaded:
            self.load()
        return sorted(self.presets.keys())
    
    def get_meshes_for_preset(self, preset_name: str) -> List[str]:
        """Get list of meshes for a specific preset"""
        if not self.loaded:
            self.load()
        
        if preset_name not in self.presets:
            return []
        return sorted(self.presets[preset_name]['meshes'])
    
    def get_attributes_for_preset(self, preset_name: str) -> Tuple[List[str], List[str]]:
        """Get required and optional attributes for a preset"""
        if not self.loaded:
            self.load()
        
        if preset_name not in self.presets:
            return [], []
        
        preset = self.presets[preset_name]
        return preset['common_attributes'], preset['optional_attributes']
    
    def get_preset_for_mesh(self, mesh_name: str) -> Optional[Tuple[str, List[str], List[str]]]:
        """Get preset info for a specific mesh name"""
        if not self.loaded:
            self.load()
        
        return self.mesh_to_preset.get(mesh_name)


# Global instance
_manager: Optional[MeshPresetManager] = None


def get_preset_manager() -> MeshPresetManager:
    """Get or create the global preset manager"""
    global _manager
    if _manager is None:
        _manager = MeshPresetManager()
    return _manager


def init_presets() -> bool:
    """Initialize the preset system from embedded data"""
    manager = get_preset_manager()
    return manager.load()
